name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
    - name: Build Site
      run: pnpm run docs:build
    - name: Deploy
      env:
        RSYNC_PWD: ${{ vars.RSYNC_PASSWORD }}
      run: |
        echo $RSYNC_PWD > rsync.pwd
        sudo chmod 600 rsync.pwd
        rsync -av --delete docs/.vuepress/dist githubactions@lib.kupars.top:30004::OWLLibrary --password-file=rsync.pwd          

