name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build Site
      run: pnpm run docs:build
    - name: Deploy
      env:
        RSYNC_PWD: ${{ vars.RSYNC_PASSWORD }}
      run: |
        echo $RSYNC_PWD > rsync.pwd
        sudo chmod 600 rsync.pwd
        rsync -av --delete docs/.vuepress/dist githubactions@lib.kupars.top:30004::OWLLibrary --password-file=rsync.pwd          

